### PR TITLE
Updated success message

### PR DESCRIPTION
**Pull request by hangwan97**
Updated according to the AZD output

### CODE REVIEW

**Comment by fangjian0423** [comment]
azd version require 1.2.0 or later, not 1.3.0. Could you pls help to update?

**Comment by hangwan97** [comment]
> azd version require 1.2.0 or later, not 1.3.0. Could you pls help to update?

Updated the version requirement.

**Review by fangjian0423 — APPROVED** [review]

**Comment by fangjian0423** [comment]
Please run `npm run update-snapshot` to generate snapshot files and commit it, otherwise the build will be failed.

**Comment by fangjian0423** [comment]
let me close it because we have a duplicated one.

**Pull request closed without merging**
